matrix:
  include:
    - language: python
      os:
        - linux
        - osx
      python:
        # 3.3 missing from Travis
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
      install:
        - cd python && pip install -r dev-requirements.txt && ./local_build.sh && cd test && pip install -r requirements.txt
      script:
        - pytest -vv -s

    - language: ruby
      os:
        - linux
        - osx
      ruby:
        - "2.1.0"
        - "2.1"
        - "2.2"
        - "2.3"
        - "2.4"
        - "2.5"
        - "2.6"
        - "2.7"
      install:
        - cd ruby && ./local_build.sh && cd test && ./install_dependencies.sh
      script:
        - ruby test_behavior.rb && ruby test_correctness.rb

    # Memory leaks
    - language: python
      os: linux
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y valgrind
      python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
      install:
        - cd python && pip install -r dev-requirements.txt && ./local_build.sh && cd test && pip install -r requirements.txt
      script:
        - rm -Rf test_correctness.py && valgrind pytest -vv -s